/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Forward-compat config object accepted from the TypeScript side.
 *
 * camelCase fields (auto-converted by napi-derive) mirror the Python
 * `TrafilaturaConfig`. `teiValidation` and `withMetadata` are accepted but
 * ignored — they keep the cross-runtime config shape stable.
 */
export interface TrafilaturaConfig {
  fast?: boolean
  favorPrecision?: boolean
  favorRecall?: boolean
  includeComments?: boolean
  includeTables?: boolean
  includeImages?: boolean
  includeFormatting?: boolean
  includeLinks?: boolean
  deduplicate?: boolean
  targetLanguage?: string
  /** Forward-compat — rs-trafilatura always returns metadata; flag is ignored. */
  withMetadata?: boolean
  onlyWithMetadata?: boolean
  /** Forward-compat — rs-trafilatura 0.2.x has no XML-TEI; flag is ignored. */
  teiValidation?: boolean
}
/** Options for a single extraction call. */
export interface ExtractOptions {
  url?: string
  /** One of `txt | markdown | json | html`. Defaults to `txt`. */
  format?: string
  config?: TrafilaturaConfig
}
/** Single-format extraction result returned to TypeScript. */
export interface ExtractionResult {
  content: string
  format: string
}
/**
 * Metadata superset returned by rs-trafilatura. Mirrors `Metadata` from the
 * upstream crate plus the `hostname` field (handy on the TS side).
 */
export interface Metadata {
  title?: string
  author?: string
  /** ISO 8601 timestamp. */
  date?: string
  description?: string
  sitename?: string
  hostname?: string
  language?: string
  categories?: Array<string>
  tags?: Array<string>
  license?: string
  image?: string
  pageType?: string
  url?: string
}
/**
 * Extract a single output format from `html`.
 *
 * # Errors
 *
 * Returns a JS `Error` when rs-trafilatura fails to parse, finds no content,
 * or the requested format is unknown.
 */
export declare function extract(html: string, options?: ExtractOptions | undefined | null): ExtractionResult
/**
 * Extract only metadata from `html`. Equivalent to calling [`extract`] with
 * `format: "txt"` and discarding the content.
 *
 * # Errors
 *
 * Returns a JS `Error` if rs-trafilatura fails to parse or finds no content.
 */
export declare function extractMetadata(html: string, url?: string | undefined | null): Metadata
/**
 * Run a single extraction and return all four formats keyed by name.
 * Defaults to `["txt", "markdown", "json", "html"]`.
 *
 * # Errors
 *
 * Returns a JS `Error` if rs-trafilatura fails.
 */
export declare function extractAllFormats(html: string, options?: ExtractOptions | undefined | null): Record<string, ExtractionResult>
