/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Subset of `rs_trafilatura::Options` exposed to JavaScript callers.
 *
 * All fields are optional; missing fields fall back to `Options::default()`.
 */
export interface TrafilaturaConfig {
  fast?: boolean
  favorPrecision?: boolean
  favorRecall?: boolean
  includeComments?: boolean
  includeTables?: boolean
  includeImages?: boolean
  includeFormatting?: boolean
  includeLinks?: boolean
  deduplicate?: boolean
  targetLanguage?: string
  withMetadata?: boolean
  onlyWithMetadata?: boolean
  teiValidation?: boolean
  urlBlacklist?: Array<string>
  authorBlacklist?: Array<string>
}
/** Per-call options for `extract` / `extractAllFormats`. */
export interface ExtractOptions {
  url?: string
  /** One of "txt", "markdown", "json", "html". Defaults to "txt". */
  format?: string
  config?: TrafilaturaConfig
}
/** Result of a single-format extraction. */
export interface ExtractionResult {
  content: string
  format: string
}
/** Document metadata extracted by `rs-trafilatura`. */
export interface Metadata {
  title?: string
  author?: string
  /** ISO 8601 date string (the underlying `chrono::DateTime<Utc>`). */
  date?: string
  description?: string
  sitename?: string
  language?: string
  url?: string
  hostname?: string
  categories?: Array<string>
  tags?: Array<string>
  license?: string
  image?: string
  pageType?: string
}
/**
 * Extract content in a single format. Returns the rendered string in the
 * requested format plus the format name. Throws when the format is unknown
 * or `rs-trafilatura` fails.
 */
export declare function extract(html: string, options?: ExtractOptions | undefined | null): ExtractionResult
/** Extract metadata only. */
export declare function extractMetadata(html: string, url?: string | undefined | null): Metadata
/**
 * Extract content in multiple formats. Defaults to `["txt", "markdown", "json"]`.
 * Failed per-format extractions are omitted from the result map.
 */
export declare function extractAllFormats(html: string, options?: ExtractOptions | undefined | null): Record<string, ExtractionResult>
