// Region replacer for `<!-- @generated:start name="<region>" -->` /
// `<!-- @generated:end name="<region>" -->` pairs. The `@generated`
// annotation matches Meta's signedsource convention used by React, Jest,
// Babel, relay-compiler, etc. for "machine-generated, do not edit".
//
// The replacer is small on purpose. Mismatched pairs, unknown region names,
// and nested regions are hard errors so a typo can never silently leave
// stale content in place.

const START_RE = /<!-- @generated:start name="([^"]+)" -->/g;
const END_RE = /<!-- @generated:end name="([^"]+)" -->/g;
const REGION_RE =
  /(<!-- @generated:start name="([^"]+)" -->)([\s\S]*?)(<!-- @generated:end name="\2" -->)/g;

export const DISCLAIMER =
  '<!-- This block is auto-generated by @contextractor/gen-md-regions. Do not edit. -->';

export interface ReplacerOptions {
  /** Map of region name → emitter that produces the markdown body. */
  emitters: Record<string, () => string>;
  /** Optional file path used in error messages. */
  source?: string;
}

export class RegionError extends Error {
  constructor(message: string, source?: string) {
    super(source ? `${source}: ${message}` : message);
    this.name = 'RegionError';
  }
}

export function rewriteRegions(input: string, opts: ReplacerOptions): string {
  validatePairs(input, opts);

  return input.replace(
    REGION_RE,
    (_full, startMarker: string, name: string, _body: string, endMarker: string) => {
      const emitter = opts.emitters[name];
      if (!emitter) {
        throw new RegionError(
          `unknown region name "${name}". Known regions: ${Object.keys(opts.emitters).join(', ') || '(none)'}`,
          opts.source,
        );
      }
      const body = emitter();
      const trimmed = body.replace(/^\n+/, '').replace(/\n+$/, '');
      return [startMarker, '', DISCLAIMER, '', trimmed, '', endMarker].join('\n');
    },
  );
}

function validatePairs(input: string, opts: ReplacerOptions): void {
  type Event = { kind: 'start' | 'end'; name: string; offset: number };
  const events: Event[] = [];
  for (const m of input.matchAll(START_RE)) {
    events.push({ kind: 'start', name: m[1] ?? '', offset: m.index ?? 0 });
  }
  for (const m of input.matchAll(END_RE)) {
    events.push({ kind: 'end', name: m[1] ?? '', offset: m.index ?? 0 });
  }
  events.sort((a, b) => a.offset - b.offset);

  const stack: Event[] = [];
  for (const event of events) {
    if (event.kind === 'start') {
      if (stack.length > 0) {
        const outer = stack[stack.length - 1];
        throw new RegionError(
          `nested regions are not allowed (start "${event.name}" inside "${outer?.name}" at offset ${event.offset})`,
          opts.source,
        );
      }
      stack.push(event);
    } else {
      const open = stack.pop();
      if (!open) {
        throw new RegionError(
          `end marker "${event.name}" without a matching start at offset ${event.offset}`,
          opts.source,
        );
      }
      if (open.name !== event.name) {
        throw new RegionError(
          `marker name mismatch: start "${open.name}" vs end "${event.name}" at offset ${event.offset}`,
          opts.source,
        );
      }
    }
  }
  if (stack.length > 0) {
    const open = stack[stack.length - 1];
    throw new RegionError(
      `mismatched markers: start "${open?.name}" at offset ${open?.offset} has no matching end`,
      opts.source,
    );
  }
}
